{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aftok.fullname" . }}-nginx
  labels:
    {{- include "aftok.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  {{- with .Values.nginx.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.nginx.tls.enabled }}
    - port: {{ .Values.nginx.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "aftok.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
